/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ferre.vista;


import com.ferre.controlador.ClienteControlador;
import com.ferre.controlador.FacturaControlador;
import com.ferre.controlador.ProductosControlador;
import com.ferre.model.Cliente;
import com.ferre.model.Factura;
import com.ferre.model.Productos;
import com.ferre.model.TOFactura;
import com.ferre.vista.MenuPrincipal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MELLO
 */
public class GenerarVenta extends javax.swing.JFrame {
    
    /**
     * Creates new form GenerarVenta
     */
    MenuPrincipal menuprincipal = new MenuPrincipal();
    ProductosControlador productosctrl = new ProductosControlador();
    List<Object> productos = new ArrayList<Object>();
    List<TOFactura> tofactura = new ArrayList<TOFactura>();
    FacturaControlador facturacontrolador = new FacturaControlador();
    ClienteControlador clientesctrl = new ClienteControlador();
    int total = 0;
    public GenerarVenta() {
        
        initComponents();
        tbl_venta.setSelectionMode(0);
        this.gettotal().setEditable(false);
    }
    public JTextField getCodigo(){
    return txt_codigoP;
    
    }
    public JTextField getIdCliente(){
    return txt_idClientef;
    
    }
    public JTextField getNombreCl(){
    return txt_nombreCl;
    
    }
    public JTextField getCantProducto(){
    return txt_cantproducto;
    
    }
    public JTextField gettotal(){
    return txt_total;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_atras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_idClientef = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nombreCl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_codigoP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cantproducto = new javax.swing.JTextField();
        Btn_addProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_venta = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        btn_facturar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(238, 238, 238));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO FERRE 2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GENERAR VENTA");

        btn_atras.setBackground(new java.awt.Color(0, 102, 204));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btn_atras.setBorderPainted(false);
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(238, 238, 238));

        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("ID CLIENTE");

        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("NOMBRE");

        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("CODIGO PRODUCTO");

        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("CANTIDAD");

        txt_cantproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantproductoActionPerformed(evt);
            }
        });

        Btn_addProducto.setBackground(new java.awt.Color(0, 153, 153));
        Btn_addProducto.setForeground(new java.awt.Color(238, 238, 238));
        Btn_addProducto.setText("AGREGAR PRODUCTO");
        Btn_addProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_addProductoActionPerformed(evt);
            }
        });

        tbl_venta.setBackground(new java.awt.Color(0, 153, 153));
        tbl_venta.setForeground(new java.awt.Color(204, 204, 204));
        tbl_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO PRODUCTO", "NOMBRE", "MEDIDA", "TIPO", "PRECIO UNIDAD ", "CANTIDAD", "SUBTOTAL"
            }
        ));
        jScrollPane1.setViewportView(tbl_venta);

        jLabel7.setForeground(new java.awt.Color(238, 238, 238));
        jLabel7.setText("TOTAL");

        txt_total.setEditable(false);
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        btn_facturar.setBackground(new java.awt.Color(0, 153, 153));
        btn_facturar.setForeground(new java.awt.Color(238, 238, 238));
        btn_facturar.setText("GENERAR VENTA");
        btn_facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturarActionPerformed(evt);
            }
        });

        btn_borrar.setBackground(new java.awt.Color(0, 153, 153));
        btn_borrar.setForeground(new java.awt.Color(238, 238, 238));
        btn_borrar.setText("BORRAR PRODUCTO");
        btn_borrar.setToolTipText("");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_idClientef)
                    .addComponent(txt_codigoP, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nombreCl)
                    .addComponent(txt_cantproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_addProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_facturar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(144, 144, 144)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_idClientef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nombreCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_codigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cantproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Btn_addProducto)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_facturar)
                    .addComponent(btn_borrar))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cantproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantproductoActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        // TODO add your handling code here:
        Ventas ventas = new Ventas();
        ventas.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void Btn_addProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_addProductoActionPerformed
        // TODO add your handling code here:
        if(this.getCodigo().getText()!="" && this.getCantProducto().getText()!=""){
            try{
                Productos product = productosctrl.getById(Integer.valueOf(this.getCodigo().getText()));
                if(product.getExistencia()<Integer.valueOf(this.getCantProducto().getText())){
                    JOptionPane.showMessageDialog(this,"El producto seleccionado no cuenta con suficientes unidades disponibles", "Error"
                    , JOptionPane.ERROR_MESSAGE);
                }else{
                    ordenarProducto(product, Integer.valueOf(getCantProducto().getText()));
                    generarTotal();
                    this.gettotal().setText(String.valueOf(total));
                
                }
                
                
            }
            
            catch(Exception c){
                JOptionPane.showMessageDialog(this,"El codigo que ingreso no pertenece a ningun producto", "Error"
                    , JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Rellene correctamente el formulario", "Advertencia"
                    , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Btn_addProductoActionPerformed

    private void btn_facturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturarActionPerformed
        // TODO add your handling code here:
       if(this.getIdCliente().getText()!=""&& this.getNombreCl().getText()!=""){
           int ganancias = this.gananciasTotales();
           Date date = new Date();
           Cliente cliente = clientesctrl.getById(Integer.valueOf(this.getIdCliente().getText()));
           Factura factura = new Factura(null,cliente,date,
                   Double.valueOf(this.gettotal().getText()),ganancias);
           facturacontrolador.save(factura, tofactura);
       }
    }//GEN-LAST:event_btn_facturarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
        int fila=tbl_venta.getSelectedRow();
        
        if(fila>=0)
        {
            
            
            int response = JOptionPane.showConfirmDialog(this, "¿Quieres eliminar este elemento?", "Advertencia",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response==JOptionPane.YES_OPTION){
                int row = fila; 
                productos.remove(row);
                tofactura.remove(row);
                limpiarTabla();
                generarTabla();
                generarTotal();
                this.gettotal().setText(String.valueOf(total));
                
            }        
             
             
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Selecciona un producto", "Advertencia"
                    , JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        menuprincipal.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_addProducto;
    public javax.swing.JButton btn_atras;
    public javax.swing.JButton btn_borrar;
    public javax.swing.JButton btn_facturar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbl_venta;
    public javax.swing.JTextField txt_cantproducto;
    public javax.swing.JTextField txt_codigoP;
    public javax.swing.JTextField txt_idClientef;
    public javax.swing.JTextField txt_nombreCl;
    public javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
    public void ordenarProducto(Productos p, Integer cantidad){
        
            int dinero = (int) (p.getPrecioVenta() * cantidad);
            Object [] dato = new Object[7];
            dato[0] = p.getCodigo();
            dato[1] = p.getNombre();
            dato[2] = p.getMedida();
            dato[3] = p.getTipo();
            dato[4] = p.getPrecioVenta();
            dato[5] =  cantidad;
            dato[6] = dinero;
            productos.add(dato);
            TOFactura tof = new TOFactura(p.getCodigo(),cantidad,p.getPrecioVenta()*cantidad,((p.getPrecioVenta()*cantidad)-(p.getPrecioCompra()*cantidad)));
            tofactura.add(tof);
             ((DefaultTableModel)tbl_venta.getModel()).addRow(dato);
            
    }
    public void generarTabla(){
    
        for(Object ob:productos){
            ((DefaultTableModel)tbl_venta.getModel()).addRow((Object[]) ob);
            
        }
    }
    public void generarTotal()
    {
        total = 0;
        int subTotal =0;
        int fila = tbl_venta.getRowCount();
        if(fila>0){
            for (int i=0;i<=fila-1;i++)
        {
            Object dinero=((DefaultTableModel)tbl_venta.getModel()).getValueAt(i, 6);
            String din = String.valueOf(dinero);
            subTotal = Integer.valueOf(din);
           
            total += subTotal;
             
            
            
        }
        }
        
        
    }
    public void limpiarTabla()
    {
        int fila = tbl_venta.getRowCount();
        for (int i=fila-1;i>=0;i--)
        {
            ((DefaultTableModel)tbl_venta.getModel()).removeRow(i);
        }
    }
    public Integer gananciasTotales(){
        int dinero = 0;
        for(TOFactura f:tofactura){
            dinero += f.getGanancia();
        }
        return dinero;
    }
    
}

